# Generated by Django 2.2.16 on 2023-03-08 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_follow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={},
        ),
    ]
